# Generated by Django 5.2.11 on 2026-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='reason',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
