# Generated by Django 5.2.11 on 2026-02-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_patientprofile_reason_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('education', models.TextField(max_length=200)),
                ('experience', models.TextField(max_length=50)),
                ('fees', models.IntegerField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bio', to='accounts.doctorprofile')),
            ],
        ),
    ]
