# Generated by Django 5.2.11 on 2026-02-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patientprofile_reason_patientprofile_age'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('time_slots', models.JSONField(default=list, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_time', to='accounts.doctorprofile')),
            ],
        ),
    ]
